cluster:
  zookeeper:
    hostPort: 192.168.245.199:2181
    sessionTimeout: 100000
agent_server:
  jetty:
    host: 172.16.42.48
    port: 10800
    context_path: /
agent_stream:
  grpc:
    host: 172.16.42.48
    port: 11800
  jetty:
    host: 172.16.42.48
    port: 12800
    context_path: /
ui:
  jetty:
    host: 172.16.42.48
    port: 12800
    context_path: /
collector_inside:
  grpc:
    host: 172.16.42.48
    port: 11800
storage:
  elasticsearch:
    cluster_name: skyOnZkevin1
    cluster_transport_sniffer: true
    cluster_nodes: 192.168.245.199:9300
    index_shards_number: 2
    index_replicas_number: 0
